

export const COUNTDOWN_LIST_REQUEST = 'COUNTDOWN_LIST_REQUEST'
export const COUNTDOWN_LIST_SUCCESS = 'COUNTDOWN_LIST_SUCCESS'
export const COUNTDOWN_LIST_FAIL = 'COUNTDOWN_LIST_FAIL'



export const COUNTDOWN_CREATE_REQUEST = 'COUNTDOWN_CREATE_REQUEST'
export const COUNTDOWN_CREATE_SUCCESS = 'COUNTDOWN_CREATE_SUCCESS'
export const COUNTDOWN_CREATE_FAIL = 'COUNTDOWN_CREATE_FAIL'

export const COUNTDOWN_DELETE_REQUEST = 'COUNTDOWN_DELETE_REQUEST'
export const COUNTDOWN_DELETE_SUCCESS = 'COUNTDOWN_DELETE_SUCCESS'
export const COUNTDOWN_DELETE_FAIL = 'COUNTDOWN_DELETE_FAIL'

export const COUNTDOWN_DETAILS_REQUEST = 'COUNTDOWN_DETAILS_REQUEST'
export const COUNTDOWN_DETAILS_SUCCESS = 'COUNTDOWN_DETAILS_SUCCESS'
export const COUNTDOWN_DETAILS_FAIL = 'COUNTDOWN_DETAILS_FAIL'
export const COUNTDOWN_DETAILS_RESET = 'COUNTDOWN_DETAILS_RESET'



export const COUNTDOWN_UPDATE_REQUEST = 'COUNTDOWN_UPDATE_REQUEST'
export const COUNTDOWN_UPDATE_SUCCESS = 'COUNTDOWN_UPDATE_SUCCESS'
export const COUNTDOWN_UPDATE_FAIL = 'COUNTDOWN_UPDATE_FAIL'
export const COUNTDOWN_UPDATE_RESET = 'COUNTDOWN_UPDATE_RESET'