export const PREDICTION_LIST_REQUEST = 'PREDICTION_LIST_REQUEST'
export const PREDICTION_LIST_SUCCESS = 'PREDICTION_LIST_SUCCESS'
export const PREDICTION_LIST_FAIL = 'PREDICTION_LIST_FAIL'


export const PREDICTION_LIST_TABLE_REQUEST = 'PREDICTION_LIST_TABLE_REQUEST'
export const PREDICTION_LIST_TABLE_SUCCESS = 'PREDICTION_LIST_TABLE_SUCCESS'
export const PREDICTION_LIST_TABLE_FAIL = 'PREDICTION_LIST_TABLE_FAIL'

export const PREDICTION_CREATE_REQUEST = 'PREDICTION_CREATE_REQUEST'
export const PREDICTION_CREATE_SUCCESS = 'PREDICTION_CREATE_SUCCESS'
export const PREDICTION_CREATE_FAIL = 'PREDICTION_CREATE_FAIL'

export const PREDICTION_DELETE_REQUEST = 'PREDICTION_DELETE_REQUEST'
export const PREDICTION_DELETE_SUCCESS = 'PREDICTION_DELETE_SUCCESS'
export const PREDICTION_DELETE_FAIL = 'PREDICTION_DELETE_FAIL'

export const PREDICTION_DETAILS_REQUEST = 'PREDICTION_DETAILS_REQUEST'
export const PREDICTION_DETAILS_SUCCESS = 'PREDICTION_DETAILS_SUCCESS'
export const PREDICTION_DETAILS_FAIL = 'PREDICTION_DETAILS_FAIL'
export const PREDICTION_DETAILS_RESET = 'PREDICTION_DETAILS_RESET'

export const PREDICTION_FIXTURE_REQUEST = 'PREDICTION_FIXTURE_REQUEST'
export const PREDICTION_FIXTURE_SUCCESS = 'PREDICTION_FIXTURE_SUCCESS'
export const PREDICTION_FIXTURE_FAIL = 'PREDICTION_FIXTURE_FAIL'
export const PREDICTION_FIXTURE_RESET = 'PREDICTION_FIXTURE_RESET'

export const PREDICTION_NUMBER_DETAILS_REQUEST = 'PREDICTION_NUMBER_DETAILS_REQUEST'
export const PREDICTION_NUMBER_DETAILS_SUCCESS = 'PREDICTION_NUMBER_DETAILS_SUCCESS'
export const PREDICTION_NUMBER_DETAILS_FAIL = 'PREDICTION_NUMBER_DETAILS_FAIL'

export const PREDICTION_UPDATE_REQUEST = 'PREDICTION_UPDATE_REQUEST'
export const PREDICTION_UPDATE_SUCCESS = 'PREDICTION_UPDATE_SUCCESS'
export const PREDICTION_UPDATE_FAIL = 'PREDICTION_UPDATE_FAIL'
export const PREDICTION_UPDATE_RESET = 'PREDICTION_UPDATE_RESET'

export const FIXTURE_REQUEST = 'FIXTURE_REQUEST'
export const FIXTURE_SUCCESS = 'FIXTURE_SUCCESS'
export const FIXTURE_FAIL = 'FIXTURE_FAIL'

export const FIXTURE_DELETE_REQUEST = 'FIXTURE_DELETE_REQUEST'
export const FIXTURE_DELETE_SUCCESS = 'FIXTURE_DELETE_SUCCESS'
export const FIXTURE_DELETE_FAIL = 'FIXTURE_DELETE_FAIL'

export const FIXTURE_SINGLE_DELETE_REQUEST = 'FIXTURE_SINGLE_DELETE_REQUEST'
export const FIXTURE_SINGLE_DELETE_SUCCESS = 'FIXTURE_SINGLE_DELETE_SUCCESS'
export const FIXTURE_SINGLE_DELETE_FAIL = 'FIXTURE_SINGLE_DELETE_FAIL'