export const PREDICTION_VIP_LIST_REQUEST = 'PREDICTION_VIP_LIST_REQUEST'
export const PREDICTION_VIP_LIST_SUCCESS = 'PREDICTION_VIP_LIST_SUCCESS'
export const PREDICTION_VIP_LIST_FAIL = 'PREDICTION_VIP_LIST_FAIL'

export const PREDICTION_VIP_CREATE_REQUEST = 'PREDICTION_VIP_CREATE_REQUEST'
export const PREDICTION_VIP_CREATE_SUCCESS = 'PREDICTION_VIP_CREATE_SUCCESS'
export const PREDICTION_VIP_CREATE_FAIL = 'PREDICTION_VIP_CREATE_FAIL'

export const PREDICTION_VIP_DELETE_REQUEST = 'PREDICTION_VIP_DELETE_REQUEST'
export const PREDICTION_VIP_DELETE_SUCCESS = 'PREDICTION_VIP_DELETE_SUCCESS'
export const PREDICTION_VIP_DELETE_FAIL = 'PREDICTION_VIP_DELETE_FAIL'

export const PREDICTION_VIP_DETAILS_REQUEST = 'PREDICTION_VIP_DETAILS_REQUEST'
export const PREDICTION_VIP_DETAILS_SUCCESS = 'PREDICTION_VIP_DETAILS_SUCCESS'
export const PREDICTION_VIP_DETAILS_FAIL = 'PREDICTION_VIP_DETAILS_FAIL'
export const PREDICTION_VIP_DETAILS_RESET = 'PREDICTION_VIP_DETAILS_RESET'

export const PREDICTION_VIP_FIXTURE_REQUEST = 'PREDICTION_VIP_FIXTURE_REQUEST'
export const PREDICTION_VIP_FIXTURE_SUCCESS = 'PREDICTION_VIP_FIXTURE_SUCCESS'
export const PREDICTION_VIP_FIXTURE_FAIL = 'PREDICTION_VIP_FIXTURE_FAIL'
export const PREDICTION_VIP_FIXTURE_RESET = 'PREDICTION_VIP_FIXTURE_RESET'

export const PREDICTION_VIP_NUMBER_DETAILS_REQUEST = 'PREDICTION_VIP_NUMBER_DETAILS_REQUEST'
export const PREDICTION_VIP_NUMBER_DETAILS_SUCCESS = 'PREDICTION_VIP_NUMBER_DETAILS_SUCCESS'
export const PREDICTION_VIP_NUMBER_DETAILS_FAIL = 'PREDICTION_VIP_NUMBER_DETAILS_FAIL'

export const PREDICTION_VIP_UPDATE_REQUEST = 'PREDICTION_VIP_UPDATE_REQUEST'
export const PREDICTION_VIP_UPDATE_SUCCESS = 'PREDICTION_VIP_UPDATE_SUCCESS'
export const PREDICTION_VIP_UPDATE_FAIL = 'PREDICTION_VIP_UPDATE_FAIL'
export const PREDICTION_VIP_UPDATE_RESET = 'PREDICTION_VIP_UPDATE_RESET'

export const FIXTURE_VIP_REQUEST = 'FIXTURE_VIP_REQUEST'
export const FIXTURE_VIP_SUCCESS = 'FIXTURE_VIP_SUCCESS'
export const FIXTURE_VIP_FAIL = 'FIXTURE_VIP_FAIL'

export const FIXTURE_VIP_DELETE_REQUEST = 'FIXTURE_VIP_DELETE_REQUEST'
export const FIXTURE_VIP_DELETE_SUCCESS = 'FIXTURE_VIP_DELETE_SUCCESS'
export const FIXTURE_VIP_DELETE_FAIL = 'FIXTURE_VIP_DELETE_FAIL'

export const FIXTURE_VIP_SINGLE_DELETE_REQUEST = 'FIXTURE_VIP_SINGLE_DELETE_REQUEST'
export const FIXTURE_VIP_SINGLE_DELETE_SUCCESS = 'FIXTURE_VIP_SINGLE_DELETE_SUCCESS'
export const FIXTURE_VIP_SINGLE_DELETE_FAIL = 'FIXTURE_VIP_SINGLE_DELETE_FAIL'