export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'


export const USER_UPDATE_PROFILE_ME_REQUEST = 'USER_UPDATE_PROFILE_ME_REQUEST'
export const USER_UPDATE_PROFILE_ME_SUCCESS = 'USER_UPDATE_PROFILE_ME_SUCCESS'
export const USER_UPDATE_PROFILE_ME_FAIL = 'USER_UPDATE_PROFILE_ME_FAIL'
export const USER_UPDATE_PROFILE_ME_RESET = 'USER_UPDATE_PROFILE_ME_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_LIST_ADMIN_REQUEST = 'USER_LIST_ADMIN_REQUEST'
export const USER_LIST_ADMIN_SUCCESS = 'USER_LIST_ADMIN_SUCCESS'
export const USER_LIST_ADMIN_FAIL = 'USER_LIST_ADMIN_FAIL'
export const USER_LIST_ADMIN_RESET = 'USER_LIST_ADMIN_RESET'

export const USER_LIST_VIP_REQUEST = 'USER_LIST_VIP_REQUEST'
export const USER_LIST_VIP_SUCCESS = 'USER_LIST_VIP_SUCCESS'
export const USER_LIST_VIP_FAIL = 'USER_LIST_VIP_FAIL'
export const USER_LIST_VIP_RESET = 'USER_LIST_VIP_RESET'

export const USER_LIST_NOTVIP_REQUEST = 'USER_LIST_NOTVIP_REQUEST'
export const USER_LIST_NOTVIP_SUCCESS = 'USER_LIST_NOTVIP_SUCCESS'
export const USER_LIST_NOTVIP_FAIL = 'USER_LIST_NOTVIP_FAIL'
export const USER_LIST_NOTVIP_RESET = 'USER_LIST_NOTVIP_RESET'

export const USER_LIST_TIPSTER_REQUEST = 'USER_LIST_TIPSTER_REQUEST'
export const USER_LIST_TIPSTER_SUCCESS = 'USER_LIST_TIPSTER_SUCCESS'
export const USER_LIST_TIPSTER_FAIL = 'USER_LIST_TIPSTER_FAIL'
export const USER_LIST_TIPSTER_RESET = 'USER_LIST_TIPSTER_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const PAYMENT_HISTORY_REQUEST = 'PAYMENT_HISTORY_REQUEST'
export const PAYMENT_HISTORY_SUCCESS = 'PAYMENT_HISTORY_SUCCESS'
export const PAYMENT_HISTORY_FAIL = 'PAYMENT_HISTORY_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'


export const SEND_SUB_EXPIRE_EMAIL_REQUEST = 'SEND_SUB_EXPIRE_EMAIL_REQUEST'
export const SEND_SUB_EXPIRE_EMAIL_SUCCESS = 'SEND_SUB_EXPIRE_EMAIL_SUCCESS'
export const SEND_SUB_EXPIRE_EMAIL_FAIL = 'SEND_SUB_EXPIRE_EMAIL_FAIL'

export const SENDEMAIL_REQUEST = 'SENDEMAIL_REQUEST'
export const SENDEMAIL_SUCCESS = 'SENDEMAIL_SUCCESS'
export const SENDEMAIL_FAIL = 'SENDEMAIL_FAIL'

